### ISSUE TITLE
unintialize variables when running V_neuron_single.m in matconvnet mode

### ISSUE THREAD

**Issue by Youmna-Salah** [donglaiw/mNeuron#1]
I have encountered a problem running V_neuron_single.m in cnn_mode='matconvnet' .The problem is always with uninitialized variables e.g. Undefined function or variable 'init_sz' ,Undefined function or variable 'neuron_id'. I am not quite sure that I am running it correctly.I would appreciate it if you mentioned exactly how to integrate your code with matconvnet example,in another words which class to run first and steps to compile and run your code.

**Comment by donglaiw** [comment]
It's fixed now. run "V_neuronInv" (parameters like 'neuron_id' are defined in this file)
